"""Transparent forecast components for request demand and workload.

The module contains three layers: a request-count distribution, an approval
outcome model, and a compound simulator that sums per-request weights. The
implementation is intentionally dependency-free so the modeling assumptions
remain visible before a later numerical fitting stack is introduced.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
import random
from typing import Sequence

from .workload import WeightedEmpiricalDistribution


@dataclass(frozen=True)
class CountForecast:
    """Predictive parameters for request arrivals in one future bucket.

    ``mean`` is the expected number of requests. ``dispersion`` controls how
    much the request count can vary around that mean; zero is the Poisson limit.
    """

    mean: float
    dispersion: float


@dataclass
class NegativeBinomialModel:
    """Negative Binomial baseline with an online demand state.

    The initial ``fit`` uses method-of-moments estimates so the repository has
    no external numerical dependency. The dynamic state then provides the
    continuous correction mechanism described by:

    ``s_(t+1) = omega + persistence * s_t + learning_rate * score_t``.

    A future implementation can replace the initial moment fit with a full
    likelihood optimizer without changing the compound forecast interface.
    """

    mean: float
    dispersion: float
    state: float = 0.0
    omega: float = 0.0
    persistence: float = 0.90
    learning_rate: float = 0.10

    @classmethod
    def fit(cls, counts: Sequence[int]) -> "NegativeBinomialModel":
        """Fit mean and dispersion by moments as a baseline.

        For a Negative Binomial with mean ``mu`` and dispersion ``phi``:

        ``variance = mu + phi * mu**2``.

        Solving this relationship gives the dispersion estimate below. If the
        observed variance is no larger than the mean, the model falls back to
        the Poisson limit with zero dispersion.
        """

        if not counts or any(count < 0 for count in counts):
            raise ValueError("counts must be non-empty and non-negative")
        mean = sum(counts) / len(counts)
        variance = sum((count - mean) ** 2 for count in counts) / len(counts)
        dispersion = max(0.0, (variance - mean) / (mean**2)) if mean else 0.0
        return cls(mean=mean, dispersion=dispersion, state=math.log(mean or 1.0))

    def forecast(self, horizon: int = 1) -> CountForecast:
        """Return the current predictive mean and dispersion.

        This baseline currently keeps one state across horizons. The explicit
        ``horizon`` argument keeps the interface ready for a later
        multi-step state transition.
        """

        if horizon < 1:
            raise ValueError("horizon must be positive")
        return CountForecast(
            mean=max(0.0, math.exp(self.state)),
            dispersion=self.dispersion,
        )

    def update(self, observed_count: int) -> CountForecast:
        """Apply a score-driven online correction after a bucket closes.

        The score is positive when the observed count exceeds the forecast and
        negative when demand was overestimated. The denominator dampens the
        correction for highly dispersed count forecasts.
        """

        forecast = self.forecast()
        score = (observed_count - forecast.mean) / (
            1.0 + forecast.dispersion * forecast.mean
        )
        self.state = (
            self.omega
            + self.persistence * self.state
            + self.learning_rate * score
        )
        return self.forecast()

    def sample_count(self, forecast: CountForecast, rng: random.Random) -> int:
        """Sample a count through the Gamma-Poisson mixture representation.

        A Negative Binomial random variable can be generated by first drawing
        a random Poisson rate from a Gamma distribution and then drawing the
        request count from that Poisson rate.
        """

        if forecast.mean <= 0.0:
            return 0
        if forecast.dispersion <= 0.0:
            return _sample_poisson(forecast.mean, rng)
        # With phi > 0, the Gamma mixing layer creates the overdispersion that
        # a Poisson-only model cannot represent.
        shape = 1.0 / forecast.dispersion
        scale = forecast.dispersion * forecast.mean
        poisson_rate = rng.gammavariate(shape, scale)
        return _sample_poisson(poisson_rate, rng)


@dataclass
class RejectionRateModel:
    """Binomial rejection-rate baseline with an online log-odds state.

    The state is stored on the log-odds scale so the forecast always remains
    between zero and one after applying the logistic transformation.
    """

    probability: float
    state: float
    persistence: float = 0.90
    learning_rate: float = 0.05

    @classmethod
    def fit(cls, decisions: int, rejected: int) -> "RejectionRateModel":
        """Fit the initial rejection probability from observed decisions."""

        if decisions <= 0 or not 0 <= rejected <= decisions:
            raise ValueError("rejected must be between zero and decisions")
        probability = min(1.0 - 1e-9, max(1e-9, rejected / decisions))
        state = math.log(probability / (1.0 - probability))
        return cls(probability=probability, state=state)

    def forecast(self) -> float:
        """Return the current rejection probability."""

        return 1.0 / (1.0 + math.exp(-self.state))

    def update(self, decisions: int, rejected: int) -> float:
        """Correct the log-odds state from a newly observed bucket.

        ``rejected - decisions * probability`` is the binomial score: it is
        positive when more requests were rejected than expected and negative
        when fewer were rejected.
        """

        if decisions <= 0 or not 0 <= rejected <= decisions:
            raise ValueError("rejected must be between zero and decisions")
        probability = self.forecast()
        score = rejected - decisions * probability
        self.state = self.persistence * self.state + self.learning_rate * score
        self.probability = self.forecast()
        return self.probability


def compound_workload_forecast(
    count_model: NegativeBinomialModel,
    rejection_model: RejectionRateModel,
    distributions: dict[str, WeightedEmpiricalDistribution],
    *,
    simulations: int = 5000,
    seed: int | None = 20260905,
) -> tuple[float, ...]:
    """Simulate total workload from count, outcome, and weight distributions.

    Each returned value is one possible total workload for the future bucket.
    The caller can use empirical quantiles of the returned sample for P80/P95
    protected capacity.
    """

    if simulations < 1:
        raise ValueError("simulations must be positive")
    rng = random.Random(seed)
    forecast = count_model.forecast()
    rejection_probability = rejection_model.forecast()
    totals: list[float] = []
    for _ in range(simulations):
        # First draw how many requests arrive. This propagates request-volume
        # uncertainty into the total workload distribution.
        request_count = count_model.sample_count(forecast, rng)
        total = 0.0
        for _ in range(request_count):
            # The approval outcome determines which workload distribution is
            # appropriate. Rejected requests do not draw backend workload.
            outcome = "rejected" if rng.random() < rejection_probability else "approved"
            total += distributions[outcome].sample(rng)
        totals.append(total)
    return tuple(sorted(totals))


def empirical_quantile(values: Sequence[float], probability: float) -> float:
    """Return a simple empirical quantile from simulated workload values."""

    if not values or not 0.0 <= probability <= 1.0:
        raise ValueError("values must be non-empty and probability must be valid")
    ordered = sorted(values)
    index = min(len(ordered) - 1, int(probability * len(ordered)))
    return ordered[index]


def _sample_poisson(rate: float, rng: random.Random) -> int:
    """Sample a Poisson value using Knuth's prototype algorithm.

    This simple implementation is easy to read and dependency-free. It is
    suitable for the small example flow, while a high-volume production
    implementation should use a vectorized or specialized sampler.
    """

    if rate <= 0.0:
        return 0
    threshold = math.exp(-rate)
    product = 1.0
    count = 0
    while product > threshold:
        count += 1
        product *= rng.random()
    return count - 1
