"""Domain objects for the IAM workload model."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class BackendTask:
    """One active backend task generated by a request."""

    task_id: str
    active_seconds: float
    capacity_units: float = 1.0

    @property
    def workload(self) -> float:
        """Capacity-unit seconds consumed by this task."""

        return self.active_seconds * self.capacity_units


@dataclass(frozen=True)
class RequestObservation:
    """Observed request-level data used to calibrate workload distributions."""

    request_id: str
    period: str
    outcome: str
    pre_workload: float = 0.0
    tasks: tuple[BackendTask, ...] = ()
    workflow_overhead_seconds: float = 0.0
    workflow_capacity_units: float = 0.0

    @property
    def backend_workload(self) -> float:
        """Active backend and orchestration workload."""

        task_workload = sum(task.workload for task in self.tasks)
        orchestration_workload = (
            self.workflow_overhead_seconds * self.workflow_capacity_units
        )
        return task_workload + orchestration_workload

    @property
    def workload(self) -> float:
        """Total capacity workload for this request."""

        backend = self.backend_workload if self.outcome == "approved" else 0.0
        return self.pre_workload + backend
