"""Domain objects for the IAM workload model.

The model deliberately keeps the request contract small. A request exposes
its approval outcome, its pre-decision work, and the backend tasks that were
actually observed. Provider-specific fields can be mapped into these objects
without leaking vendor terminology into the forecasting layer.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class BackendTask:
    """One active backend task generated by a request.

    ``active_seconds`` is active execution time, not time spent waiting in a
    queue. ``capacity_units`` allows a task to consume more or less than one
    unit, which is useful when the capacity resource is not a single worker.
    """

    task_id: str
    active_seconds: float
    capacity_units: float = 1.0

    @property
    def workload(self) -> float:
        """Return capacity-unit seconds consumed by this task.

        This is the resource-time measure that can be added across parallel
        tasks. It is intentionally different from the request's wall-clock
        service time.
        """

        return self.active_seconds * self.capacity_units


@dataclass(frozen=True)
class RequestObservation:
    """Observed request data used to calibrate workload distributions.

    ``period`` is the time bucket used for aggregation. ``outcome`` is kept as
    a string at this modeling stage so an adapter can map a provider's status
    values into ``approved`` or ``rejected`` without changing the model.
    """

    request_id: str
    period: str
    outcome: str
    pre_workload: float = 0.0
    tasks: tuple[BackendTask, ...] = ()
    workflow_overhead_seconds: float = 0.0
    workflow_capacity_units: float = 0.0

    @property
    def backend_workload(self) -> float:
        """Return active post-approval backend task workload.

        This property deliberately excludes approval-workflow orchestration.
        Backend tasks are conditional on approval, while the workflow engine
        has already consumed capacity calculating the approval steps and
        approvers even when the final outcome is rejected.
        """

        # Summing task resource-time preserves the capacity consumed by tasks
        # that run concurrently; using only elapsed request time would lose it.
        return sum(task.workload for task in self.tasks)

    @property
    def workflow_workload(self) -> float:
        """Return active approval-workflow capacity consumption.

        This covers workflow-engine execution such as calculating approval
        steps, resolving approvers, and routing the request. It excludes time
        spent waiting for a human approval. Because this work happens before
        the outcome is known, it is charged to both approved and rejected
        requests.
        """

        return self.workflow_overhead_seconds * self.workflow_capacity_units

    @property
    def workload(self) -> float:
        """Return total workload under the approval-outcome contract.

        A rejected request still has pre-decision cost and approval-workflow
        execution cost, but it does not receive post-approval backend task
        cost when rejection happens before activation.
        """

        # Workflow execution is unconditional: the workflow engine calculates
        # the approval route before the request is approved or rejected.
        # Only post-approval backend tasks are gated by the outcome.
        backend = self.backend_workload if self.outcome == "approved" else 0.0
        return self.pre_workload + self.workflow_workload + backend
